version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: scheduling_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: scheduling
      MYSQL_DATABASE: scheduling
      MYSQL_USER: scheduling
      MYSQL_PASSWORD: scheduling
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: